# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_configpanel.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConfigPanel(object):
    def setupUi(self, Ui_ConfigPanel):
        Ui_ConfigPanel.setObjectName("Ui_ConfigPanel")
        Ui_ConfigPanel.resize(532, 666)
        Ui_ConfigPanel.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.centralwidget = QtWidgets.QWidget(Ui_ConfigPanel)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 501, 80))
        self.groupBox.setObjectName("groupBox")
        self.label_host = QtWidgets.QLabel(self.groupBox)
        self.label_host.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_host.setObjectName("label_host")
        self.label_port = QtWidgets.QLabel(self.groupBox)
        self.label_port.setGeometry(QtCore.QRect(10, 50, 91, 21))
        self.label_port.setObjectName("label_port")
        self.line_host = QtWidgets.QLineEdit(self.groupBox)
        self.line_host.setEnabled(False)
        self.line_host.setGeometry(QtCore.QRect(110, 20, 381, 20))
        self.line_host.setObjectName("line_host")
        self.line_port = QtWidgets.QLineEdit(self.groupBox)
        self.line_port.setGeometry(QtCore.QRect(110, 50, 381, 20))
        self.line_port.setObjectName("line_port")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 501, 421))
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_trigs_params = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_trigs_params.setGeometry(QtCore.QRect(10, 50, 481, 281))
        self.table_trigs_params.setObjectName("table_trigs_params")
        self.table_trigs_params.setColumnCount(4)
        self.table_trigs_params.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_trigs_params.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_trigs_params.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_trigs_params.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_trigs_params.setHorizontalHeaderItem(3, item)
        self.add_trig = QtWidgets.QPushButton(self.groupBox_2)
        self.add_trig.setGeometry(QtCore.QRect(470, 340, 21, 23))
        self.add_trig.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/iconfinder_Create_132699.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_trig.setIcon(icon)
        self.add_trig.setObjectName("add_trig")
        self.del_trig = QtWidgets.QPushButton(self.groupBox_2)
        self.del_trig.setGeometry(QtCore.QRect(440, 340, 21, 23))
        self.del_trig.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/iconfinder_Cancel_132620.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_trig.setIcon(icon1)
        self.del_trig.setObjectName("del_trig")
        self.combo_program = QtWidgets.QComboBox(self.groupBox_2)
        self.combo_program.setGeometry(QtCore.QRect(10, 20, 331, 22))
        self.combo_program.setObjectName("combo_program")
        self.combo_program.addItem("")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 350, 421, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_name_file = QtWidgets.QLabel(self.groupBox_4)
        self.label_name_file.setGeometry(QtCore.QRect(60, 20, 351, 21))
        self.label_name_file.setObjectName("label_name_file")
        self.button_select_file = QtWidgets.QPushButton(self.groupBox_4)
        self.button_select_file.setGeometry(QtCore.QRect(10, 20, 41, 23))
        self.button_select_file.setObjectName("button_select_file")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(400, 10, 111, 31))
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setEnabled(False)
        self.button_stop.setGeometry(QtCore.QRect(280, 10, 111, 31))
        self.button_stop.setAutoDefault(False)
        self.button_stop.setDefault(False)
        self.button_stop.setFlat(False)
        self.button_stop.setObjectName("button_stop")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 560, 231, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.line_low_freq = QtWidgets.QLineEdit(self.groupBox_3)
        self.line_low_freq.setGeometry(QtCore.QRect(40, 20, 61, 21))
        self.line_low_freq.setObjectName("line_low_freq")
        self.line_high_freq = QtWidgets.QLineEdit(self.groupBox_3)
        self.line_high_freq.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.line_high_freq.setObjectName("line_high_freq")
        self.label_low = QtWidgets.QLabel(self.groupBox_3)
        self.label_low.setGeometry(QtCore.QRect(20, 20, 21, 21))
        self.label_low.setObjectName("label_low")
        self.label_high = QtWidgets.QLabel(self.groupBox_3)
        self.label_high.setGeometry(QtCore.QRect(120, 20, 31, 21))
        self.label_high.setObjectName("label_high")
        self.checkBox_trigEmul = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_trigEmul.setGeometry(QtCore.QRect(40, 10, 131, 17))
        self.checkBox_trigEmul.setObjectName("checkBox_trigEmul")
        Ui_ConfigPanel.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_ConfigPanel)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 532, 21))
        self.menubar.setObjectName("menubar")
        Ui_ConfigPanel.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_ConfigPanel)
        self.statusbar.setObjectName("statusbar")
        Ui_ConfigPanel.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_ConfigPanel)
        QtCore.QMetaObject.connectSlotsByName(Ui_ConfigPanel)

    def retranslateUi(self, Ui_ConfigPanel):
        _translate = QtCore.QCoreApplication.translate
        Ui_ConfigPanel.setWindowTitle(_translate("Ui_ConfigPanel", "Configuration Panel"))
        self.groupBox.setTitle(_translate("Ui_ConfigPanel", "Brainamp configuation"))
        self.label_host.setText(_translate("Ui_ConfigPanel", "Host"))
        self.label_port.setText(_translate("Ui_ConfigPanel", "Port"))
        self.line_host.setText(_translate("Ui_ConfigPanel", "127.0.0.1"))
        self.line_port.setText(_translate("Ui_ConfigPanel", "51244"))
        self.groupBox_2.setTitle(_translate("Ui_ConfigPanel", "Trigger configuration"))
        item = self.table_trigs_params.horizontalHeaderItem(0)
        item.setText(_translate("Ui_ConfigPanel", "label"))
        item = self.table_trigs_params.horizontalHeaderItem(1)
        item.setText(_translate("Ui_ConfigPanel", "left sweep"))
        item = self.table_trigs_params.horizontalHeaderItem(2)
        item.setText(_translate("Ui_ConfigPanel", "right sweep"))
        item = self.table_trigs_params.horizontalHeaderItem(3)
        item.setText(_translate("Ui_ConfigPanel", "max stack"))
        self.combo_program.setItemText(0, _translate("Ui_ConfigPanel", "New Parameters"))
        self.groupBox_4.setTitle(_translate("Ui_ConfigPanel", "Select Template"))
        self.label_name_file.setText(_translate("Ui_ConfigPanel", "File name"))
        self.button_select_file.setText(_translate("Ui_ConfigPanel", "File"))
        self.button_start.setText(_translate("Ui_ConfigPanel", "Start"))
        self.button_stop.setText(_translate("Ui_ConfigPanel", "Stop"))
        self.groupBox_3.setTitle(_translate("Ui_ConfigPanel", "Passband Filter"))
        self.line_low_freq.setText(_translate("Ui_ConfigPanel", "1"))
        self.line_high_freq.setText(_translate("Ui_ConfigPanel", "20"))
        self.label_low.setText(_translate("Ui_ConfigPanel", "Low"))
        self.label_high.setText(_translate("Ui_ConfigPanel", "High"))
        self.checkBox_trigEmul.setText(_translate("Ui_ConfigPanel", "triggers emulation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_ConfigPanel = QtWidgets.QMainWindow()
    ui = Ui_Ui_ConfigPanel()
    ui.setupUi(Ui_ConfigPanel)
    Ui_ConfigPanel.show()
    sys.exit(app.exec_())
